# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f54bcc2577648cefde7cfdb9f87308fea8ff828500dcef24f67d8585039f4de6099cb94372471cb7342282f276c640ff7fcc59c5f375fbc57e57a41a2b808cc1

test:
  secret_key_base: 50c701fada9794f1429be78a70d546003ee5d5f3ee8a9997c914ce24131883a576bc6920868db2ab8a549dbaf104d4e9aa68805628c3035a82e7535cf1c4c320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
